name: Deploy Api Docs
on: 
  push:
    branches: [main]
jobs:
  create-deployment-artifacts:
    name: Create Deployment Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install node, redoc-cli
        uses: actions/setup-node@v2

      - name: Install redoc-cli
        run: |
          npm install -g redoc-cli

      - name: Generate static html
        run: |
          redoc-cli bundle ./openapi-schemas/hello/helloworld.swagger.json -o build/hellowworld.html
          redoc-cli bundle ./openapi-schemas/petstore/petstore.json -o build/petstore.html
          redoc-cli bundle ./openapi-schemas/petstore/petstore-v2.json -o build/petstore-v2.html

      - name: Create deplyment artifacts
        run: tar -czf ${{ github.sha }}.tar.gz build

      - name: Store Artifacts for Distribution
        uses: actions/upload-artifact@v2
        with:
          name: api-doc-build
          path: ${{ github.sha }}.tar.gz

  prepare-release-artifacts:
    name: Prepare Release Artifacts
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts
    steps:
      - name: Download artifact
      - uses: actions/download-artifact@v2
        with: 
          name: api-doc-build

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }} # host address
          username: ${{ secrets.USERNAME }} # username to access this host
          port: ${{ secrets.PORT }} # file transfer port
          key: ${{ secrets.API_KEY }} # you will get this key by cat ~/.ssh/id_rsa
          source: ${{ github.sha }}.tar.gz # zipped artifact name
          target: ${{ secrets.TARGET }} # root dir of the remote web server

      - name: Extract archive
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.API_KEY }}
          script: | 
            tar xzf ${{ secrets.TARGET }}/${{ github.sha }}.tar.gz -C ${{ secrets.TARGET }}
            mv ${{ secrets.TARGET }}/build/* ${{ secrets.TARGET }}

      - name: Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.API_KEY }}
          script: |
            rm -rf ${{ secrets.TARGET }}/build
            rm ${{ secrets.TARGET }}/${{ github.sha }}.tar.gz
