name: Deploy Api Docs
on: 
  push:
    branches: [main]
jobs:
  create-deployment-artifacts:
    name: Create Deployment Artifacts.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node,Redoc
        uses: actions/setup-node@v2

      - name: "Generate static html"
        run: |
          npm install -g redoc-cli
          redoc-cli build ./openapi-schemas/hello/helloworld.swagger.json
          mv helloworld.swagger.json build/hellowworld.html

      - name: Create Deployment Artifacts
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${{ GITHUB_SHA }}".tar.gz *

      - name: Store Artifacts for Distribution
        uses: actions/upload-artifact@v2
        with:
          name: api-doc-build
          path: ${{ github.sha }}.tar.gz 
